version: '3'

vars:
  CONTAINER:
    sh: docker ps -f status=running --format {{ "\"{{.Image}} {{.Names}}\"" }} | grep vsc-pico-synth | cut -f 2 -d " "

tasks:
  build:
    desc: Build all artifacts
    cmds:
      - task: build-target
      - task: build-host

  dev:
    desc: Verify specs on host in watch mode
    watch: true
    sources:
      - 'source/**/*.cc'
      - 'source/**/*.h'
    cmds:
      - clear
      - task: specs-host

  specs-host:
    desc: Verify specs on host
    deps:
      - build-host
    cmds:
      - docker exec -it --env CTEST_OUTPUT_ON_FAILURE=1 "{{.CONTAINER}}" cmake --build /build/host --target test

  specs-target:
    desc: Download specs to target
    deps:
      - build-target
    cmds:
      - docker cp "{{.CONTAINER}}:/build/pico/library/specs/library-specs.uf2" /run/media/$USER/RPI-RP2/
    preconditions:
      - sh: picotool info
        msg: "Requires Pico in BOOTSEL mode"

  build-host:
    internal: true
    deps:
      - use-container
    cmds: 
      - docker exec -it "{{.CONTAINER}}" cmake --build /build/host --target all

  build-target:
    internal: true
    deps:
      - use-container
    cmds: 
      - docker exec -it "{{.CONTAINER}}" cmake --build /build/pico --target all

  use-container:
    internal: true
    preconditions:
      - sh: test ! -z "{{.CONTAINER}}"
        msg: "Container 'vsc-pico-synth' is not running."
    requires:
      vars: [CONTAINER]
