version: '3'

env:
  PICO_SDK_PATH: '{{ joinPath .ROOT_DIR "_build/ext/pico-sdk" }}'

tasks:
  build:
    desc: Build all artifacts
    cmds:
      - task: build-host
      - task: build-pico

  dev:
    desc: Verify specs on host in watch mode
    watch: true
    sources:
      - 'source/host/**/*.cc'
      - 'source/host/**/*.h'
      - 'source/shared/**/*.cc'
      - 'source/shared/**/*.h'
    cmds:
      - clear
      - task: specs-host

  specs-host:
    desc: Verify specs on host
    deps:
      - build-host
    dir: source
    cmds:
      - ctest --preset "host-clang"

  build-host:
    internal: true
    cmds:
      - cmake --build --preset "host-clang" --target all
    dir: source
    deps:
      - configure-host

  build-pico:
    internal: true
    cmds:
      - cmake --build --preset "pico" --target all
    dir: source
    deps:
      - configure-pico

  configure-host:
    internal: true
    cmds:
      - cmake --preset "host-clang"
    dir: source
    status:
      - test -d {{ joinPath .ROOT_DIR "_build/host-clang" }}
      - test -f {{ joinPath .ROOT_DIR "_build/host-clang/CMakeCache.txt" }}

  configure-pico:
    internal: true
    cmds:
      - cmake --preset "pico"
    dir: source
    deps:
      - pico-sdk
    status:
      - test -d {{ joinPath .ROOT_DIR "_build/pico" }}
      - test -f {{ joinPath .ROOT_DIR "_build/pico/CMakeCache.txt" }}

  pico-sdk:
    desc: Download and install the Pico SDK
    cmds:
      - git clone https://github.com/raspberrypi/pico-sdk.git _build/ext/pico-sdk
      - cd _build/ext/pico-sdk && git switch -c raphaelmeyer/1.5.1 1.5.1
      - cd _build/ext/pico-sdk && git submodule update --init
    status:
      - test -d _build/ext/pico-sdk
      - test -f _build/ext/pico-sdk/CMakeLists.txt
